name: Run tests
on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2

      - name: mkdir build folder
        run: mkdir -p myxmlpp/build
      - name: cmake build
        run: cmake -Bmyxmlpp/build -H.
      - run : gcc -v
      - name: build unit test
        run: cmake --build myxmlpp/build --target unit-tests --parallel 2
      - name: run tests
        run: cd myxmlpp && ./unit-tests

