name: Run tests
on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: alexjub94/updated-criterion
    steps:
      - uses: actions/checkout@v2

      - name: mkdir build folder
        run: mkdir -p myxmlpp/build
      - name: cmake build
        run: cmake -Bmyxmlpp/build -H.
      - run : gcc -v
      - name: build unit test
        run: cmake --build myxmlpp/build --target unit-tests --parallel 2
      - name: run tests
        run: cd myxmlpp && ./unit-tests --json=tests_report.json || echo ""
      - name: interpret-criterion-action
        uses: alexjub94/interpret-criterion-action@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reportFilepath: myxmlpp/tests_report_json


